from manim import *

class InExPrinciple(Scene):
    def construct(self):
        eq = VGroup()
        eq += MathTex(r"|A_1 \cup A_2 \cup \cdots \cup A_n|")
        eq += MathTex(r"= \sum{|A_i|}",color = BLUE_B)
        eq += MathTex(r"- \sum{|A_i \cap A_j |}",color = GREEN)
        eq += MathTex(r"+ \sum{|A_i \cap A_j \cap A_k|}",color = PINK)
        eq += MathTex(r"- \sum{|A_i \cap A_j \cap A_k \cap A_l|}",color = ORANGE)
        eq += MathTex(r"\cdots")
        eq += MathTex(r"+(-1)^{n+1} |A_1 \cap A_2 \cap \cdots \cap A_n|")
        eq.arrange(DOWN,aligned_edge = LEFT,buff = 0.3).to_edge(UL,buff = 1)
        eq[0].shift(RIGHT*0.5)

        eq3 = VGroup()
        eq3 += MathTex(r"+ C_3^1",color = PINK).next_to(eq[1],buff = 1)
        eq3 += MathTex(r"- C_3^2",color = PINK).next_to(eq[2],buff = 1)
        
        eq4 = VGroup()
        eq4 += MathTex(r"+ C_4^1",color = ORANGE).next_to(eq[1],buff = 1)
        eq4 += MathTex(r"- C_4^2",color = ORANGE).next_to(eq[2],buff = 1)
        eq4 += MathTex(r"+ C_4^3",color = ORANGE).next_to(eq[3],buff = 1)

        self.play(Write(eq[0]))
        self.wait()
        self.play(Write(eq[1]))
        self.wait()
        self.play(Write(eq[2]))
        self.wait()
        self.play(Write(eq3[0]))
        self.play(Write(eq3[1]))
        self.wait()
        self.play(Write(eq[3]),Unwrite(eq3))
        self.wait()
        self.play(Write(eq4[0]))
        self.play(Write(eq4[1]))
        self.play(Write(eq4[2]))
        self.wait()
        self.play(Write(eq[4]),Unwrite(eq4))
        self.wait()
        self.play(Write(eq[5]),Write(eq[6]))
        self.play(eq.animate.set_color(WHITE))
        self.wait()